#kubectl create ns apache-poc-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: apache-ns-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
